binop_separator = "Front"
condense_wildcard_suffixes = true
edition = "2021"
error_on_line_overflow = false
error_on_unformatted = false
fn_single_line = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = 'StdExternalCrate'
imports_granularity = 'One'
imports_layout = 'HorizontalVertical'
match_block_trailing_comma = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
trailing_semicolon = false
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = 'Two'
where_single_line = true
wrap_comments = true
